### ISSUE TITLE
How to run this app ?

### ISSUE THREAD

**Issue by bismoy2013** [jackrabbitsgroup/angular-google-auth#1]
[~/angular-google-auth](master) -> node google-auth.min.js 

/home/bismoy/angular-google-auth/google-auth.min.js:1
on (exports, require, module, __filename, __dirname) { "use strict";angular.mo
                                                                    ^
ReferenceError: angular is not defined
    at Object.<anonymous> (/home/bismoy/angular-google-auth/google-auth.min.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by imjakechapman** [comment]
@bismoy2013 This isn't a full application, this is just the angular module.

You can easily generator a simple angular application with https://github.com/yeoman/generator-angular and install this module, include it into your angular application and try it out that way.
